spring:
  application:
    name: demo
    
management:
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      newrelic:
        enabled: true

        
logging:
  level:
    io:
      micrometer:
        newrelic: trace