apiVersion: apps/v1
kind: Deployment
metadata:
  name: springwithnewrelic
spec:
  selector:
    matchLabels:
      app: springwithnewrelic
  template:
    metadata:
      labels:
        app: springwithnewrelic
    spec:
      containers:
      - name: springwithnewrelic
        image: springwithnewrelic
        ports:
        - containerPort: 8080
        env:
        - name: NEW_RELIC_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: newreliclicensekey
              key: LICENCE
