apiVersion: apps/v1
kind: Deployment
metadata:
  name: springwithnewrelic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springwithnewrelic
  template:
    metadata:
      labels:
        app: springwithnewrelic
    spec:
      containers:
      - name: springwithnewrelic
        image: springwithnewrelic
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
