apiVersion: apps/v1
kind: Deployment
metadata:
  name: springwithnewrelic
spec:
  selector:
    matchLabels:
      app: springwithnewrelic
  template:
    metadata:
      labels:
        app: springwithnewrelic
    spec:
      containers:
      - name: springwithnewrelic
        image: springwithnewrelic
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: MANAGEMENT_METRICS_EXPORT_NEWRELIC_APIKEY
          valueFrom:
            secretKeyRef:
              name: newrelicsecret
              key: apikey
        - name: MANAGEMENT_METRICS_EXPORT_NEWRELIC_ACCOUNTID
          valueFrom:
            secretKeyRef:
              name: newrelicsecret
              key: accountid
