apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml

namespace: spring-newrelic

images:
- name: springwithnewrelic
  newName: geraldocoosta/springboot-newrelic
  newTag: 7913f4d2109402dbeb7dccaf30b2f7c49abdda75
