apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml

namespace: spring-newrelic

images:
- name: springwithnewrelic
  newName: geraldocoosta/springboot-newrelic
  newTag: d2d80e194ca9fa25e99faeafb97bda9e5af284a7
