apiVersion: v1
kind: Service
metadata:
  name: springwithnewrelic-service
spec:
  selector:
    app: springwithnewrelic
  ports:
  - port: 8080
    targetPort: 8080
  env:
    - name: NEW_RELIC_LICENSE_KEY
      valueFrom:
        secretKeyRef:
          name: newreliclicensekey
          key: LICENCE
